---
title: "April 5th Milestone"
author: "Andres de Loera-Brust"
date: "April 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#I begin as always by loading in the libraries I will use. 
library(janitor)
library(sf)
library(fs)
library(readxl)
library(tidyverse)

```

```{r importation, echo = FALSE, warning = FALSE}
#This code chunk imports the some of the data I will be using. 
#First off is the data on the beneficiaries assigned to Medicare Shared Savings Program (MSSP) Acountable care Organizations (ACOs). 
  #The unit of observation is the ACO-county: each entry is data on an ACO's beneficiary population in a certain county. This data can be collapsed to either the ACO level or the county level, depending on project needs.
  #This data is made available by the Center for Medicare and Medicaid Services (CMS).
  #I will use this data to create a dynamic map showing the Medicare beneficiary population assigned to ACOs over time. 
  #So far I have only created the map included below.
#Other graphics will be made using the public use files on each ACO organizations, found at the link below: https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SSPACO/index.html

#Now to download the data: I start with 2017. 
  #First I download the zip file directly from the CMS website.
download.file(url = "https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SSPACO/Downloads/ACOSSPCOUNTYASSIGNEDPUF2017.zip",
              dest = "aco_county_2017puf.zip",
              mode = "wb")
  #Second I untar the zip file to get the dictionary and spreadsheet available in my workspace.
untar("aco_county_2017puf.zip")
  #Third I read the csv file into an r object, which for now I keep roughly in the original format.
aco_county_benes_2017 <- read_csv("ACO.SSP.COUNTY.ASSIGNED.PUF.2017.csv") %>%
    #I call clean names for ease of use
  clean_names() %>%
    #I create a numeric total beneficiaries variable.
  mutate(total_benes = as.numeric(tot_ab),
         total_benes = replace_na(total_benes, 0)) %>%
    #Finally I select just the variables I will want later.
  select(year, aco_id, state_name, county_name, state_id, county_id, total_benes)

#I repeat the process for 2016: 
  #First I download the zip file directly from the CMS website.
download.file(url = "https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SSPACO/Downloads/ACOSSPCOUNTYASSIGNEDPUF2016.zip",
              dest = "aco_county_2016puf.zip",
              mode = "wb")
  #Second I untar the zip file to get the dictionary and spreadsheet available in my workspace.
untar("aco_county_2016puf.zip")
  #Third I read the csv file into an r object, which for now I keep roughly in the original format.
aco_county_benes_2016 <- read_csv("ACO.SSP.COUNTY.ASSIGNED.PUF.2016.csv") %>%
    #I call clean names for ease of use
  clean_names() %>%
    #I create a numeric total beneficiaries variable.
  mutate(total_benes = as.numeric(tot_ab),
         total_benes = replace_na(total_benes, 0)) %>%
    #Finally I select just the variables I will want later.
  select(year, aco_id, state_name, county_name, state_id, county_id, total_benes)

#I repeat the same process for 2015: 
  #First I download the zip file directly from the CMS website.
download.file(url = "https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SSPACO/Downloads/ACOSSPCOUNTYASSIGNEDPUF2015.zip",
              dest = "aco_county_2015puf.zip",
              mode = "wb")
  #Second I untar the zip file to get the dictionary and spreadsheet available in my workspace.
untar("aco_county_2015puf.zip")
  #Third I read the csv file into an r object, which for now I keep roughly in the original format.
aco_county_benes_2015 <- read_csv("ACO.SSP.COUNTY.ASSIGNED.PUF.2015.csv") %>%
    #I call clean names for ease of use
  clean_names() %>%
    #I create a numeric total beneficiaries variable.
  mutate(total_benes = as.numeric(tot_ab),
         total_benes = replace_na(total_benes, 0)) %>%
    #Finally I select just the variables I will want later.
  select(year, aco_id, state_name, county_name, state_id, county_id, total_benes)

#I now repeat the process one last time for 2014: 
  #First I download the zip file directly from the CMS website.
download.file(url = "https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SSPACO/Downloads/ACOSSPCOUNTYASSIGNEDPUF2014.zip",
              dest = "aco_county_2014puf.zip",
              mode = "wb")
  #Second I untar the zip file to get the dictionary and spreadsheet available in my workspace.
untar("aco_county_2014puf.zip")
  #Third I read the csv file into an r object, which for now I keep roughly in the original format.
aco_county_benes_2014 <- read_csv("ACO.SSP.COUNTY.ASSIGNED.PUF.2014.csv") %>%
    #I call clean names for ease of use
  clean_names() %>%
    #I create a numeric total beneficiaries variable.
  mutate(total_benes = as.numeric(tot_ab),
         total_benes = replace_na(total_benes, 0)) %>%
    #Finally I select just the variables I will want later.
  select(year, aco_id, state_name, county_name, state_id, county_id, total_benes)


#Now I import a US map shapefile to be able to do mapping

#This comes from the census bureau, which makes map files of the US like the one I will use publicly available.
#I start by downloading a zip file with several file versions of a US county level map.
download.file(url = "https://www2.census.gov/geo/tiger/GENZ2016/shp/cb_2016_us_county_500k.zip",
              dest = "county_shapefile.zip",
              mode = "wb")
#I untar the zip file.
untar("county_shapefile.zip")
#And finally I save the shapefile I want as an r object. 
county_map <- read_sf("cb_2016_us_county_500k.shp") %>%
  clean_names()

```


```{r manipulation, echo = FALSE, warning = FALSE}
#I begin by collapsing each of the ACO-county level datasets to the county level. 
#For now I just want the raw number of ACO beneficiaries in each county

#Starting with the 2017 data:
county_lvl_aco_2017 <- aco_county_benes_2017 %>%
  #I group by state and county identifiers.
  group_by(state_name, county_name, state_id, county_id) %>%
  #Then I summarize to get the total number of ACO beneficiaries and add a year variable. 
  summarize(aco_benes = sum(total_benes), year  = 2017) %>%
  #Finally I select just the variables I'll use to merging and mapping.
  select(state_name, county_name, aco_benes, year)

#I now apply the same process to the other years, beginning with 2016
county_lvl_aco_2016 <- aco_county_benes_2016 %>%
  #I group by state and county identifiers.
  group_by(state_name, county_name, state_id, county_id) %>%
  #Then I summarize to get the total number of ACO beneficiaries and add a year variable. 
  summarize(aco_benes = sum(total_benes), year  = 2016) %>%
  #Finally I select just the variables I'll use to merging and mapping.
  select(state_name, county_name, aco_benes, year)

#2015
county_lvl_aco_2015 <- aco_county_benes_2015 %>%
  #I group by state and county identifiers.
  group_by(state_name, county_name, state_id, county_id) %>%
  #Then I summarize to get the total number of ACO beneficiaries and add a year variable. 
  summarize(aco_benes = sum(total_benes), year  = 2015) %>%
  #Finally I select just the variables I'll use to merging and mapping.
  select(state_name, county_name, aco_benes, year)

#2014
county_lvl_aco_2014 <- aco_county_benes_2014 %>%
  #I group by state and county identifiers.
  group_by(state_name, county_name, state_id, county_id) %>%
  #Then I summarize to get the total number of ACO beneficiaries and add a year variable. 
  summarize(aco_benes = sum(total_benes), year  = 2014) %>%
  #Finally I select just the variables I'll use to merging and mapping.
  select(state_name, county_name, aco_benes, year)

#Here I restrict the county map shapefile to just the continental united states for the sake of better visualization.

#I start by reading in my handmade file linking the FIPS codes and state names for the continental US
state_names_codes <- read_xlsx("state_names_codes.xlsx")

#Then I make a new dataset which filters the previous one by the vector above and adds state names
continental_county_shapes <- county_map %>%
  #I mutate the statefp codes to numeric to align with the other dataset.
  mutate(statefp = as.numeric(statefp)) %>%
  #Then I filter by the codes of the continental states. 
  filter(statefp %in% state_names_codes$statefp) %>%
  #I then merge with the state names file I made to get state names too.
  left_join(state_names_codes, by = "statefp") %>%
  #I also take the opportunity to select just the variables I will need for merging or for mapping.
  select(state_name, name, geometry) 

#Finally I will merge all my datasets together to create the master file I can use to map. 
#First I add the shape data to each years dataset
#So I start with the 2017 county level ACO data.
temp_2017 <- county_lvl_aco_2017 %>%
  #Then I remove states not in the continental US.
  filter(state_name != "Alaska", state_name != "Hawaii") %>%
  #Then I merge with the shape information.
  full_join(continental_county_shapes, by = c("state_name" = "state_name", "county_name" = "name")) %>%
  #Finally I just select the data I will use.
  ungroup() %>%
  select(state_name, county_name, aco_benes, year, geometry)

#I repeat the process with the 2016 data:
temp_2016 <- county_lvl_aco_2016 %>%
  #Then I remove states not in the continental US.
  filter(state_name != "Alaska", state_name != "Hawaii") %>%
  #Then I merge with the shape information.
  full_join(continental_county_shapes, by = c("state_name" = "state_name", "county_name" = "name")) %>%
  #Finally I just select the data I will use.
  ungroup() %>%
  select(state_name, county_name, aco_benes, year, geometry)

#And again with 2015: 
temp_2015 <- county_lvl_aco_2015 %>%
  #Then I remove states not in the continental US.
  filter(state_name != "Alaska", state_name != "Hawaii") %>%
  #Then I merge with the shape information.
  full_join(continental_county_shapes, by = c("state_name" = "state_name", "county_name" = "name")) %>%
  #Finally I just select the data I will use.
  ungroup() %>%
  select(state_name, county_name, aco_benes, year, geometry)

#Finally with 2014: 
temp_2014 <- county_lvl_aco_2014 %>%
  #Then I remove states not in the continental US.
  filter(state_name != "Alaska", state_name != "Hawaii") %>%
  #Then I merge with the shape information.
  full_join(continental_county_shapes, by = c("state_name" = "state_name", "county_name" = "name")) %>%
  #Finally I just select the data I will use.
  ungroup() %>%
  select(state_name, county_name, aco_benes, year, geometry)

#Now I merge all of these datasets together "vertically" to create a master dataset where the unit of observation is a county year and the important data is the geometry and the number of beneficiaries. 
master <- rbind(temp_2017, temp_2016, temp_2015, temp_2014)

```

```{r visualization, echo = FALSE, cache = TRUE}



```


